---
title: "Untitled"
output: html_document
date: "2022-10-12"
---

## Initial Setup

```{r initial-setup, eval=T, echo=FALSE, include=FALSE}
#install.packages('reticulate')
reticulate::virtualenv_create('testEnv')
reticulate::use_virtualenv('testEnv')
reticulate::virtualenv_install('testEnv', packages = 'numpy')
reticulate::virtualenv_install('testEnv', packages = 'matplotlib')
reticulate::virtualenv_install('testEnv', packages = 'pandas')
reticulate::virtualenv_install('testEnv', packages = 'scipy')

reticulate::virtualenv_install('testEnv', packages = 'plotnine')
reticulate::virtualenv_install('testEnv', packages = 'dpython')
#reticulate::virtualenv_install('testEnv', packages = 'sklearn')
```


## Setup Block
```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
reticulate::use_virtualenv('testEnv')
```

## boxplot of pushups based on position
```{python}

pushupsData.boxplot(column='pushups',by= 'position')
#plt.show()

#print(f"pushups: {pushupsData['pushups']}")
#print(f"positon: {pushupsData['position']}")
```
This boxplot shows skill guys do more


```{python}
import pandas as pd
from plotnine import ggplot, aes, geom_histogram, geom_boxplot
  
# reading dataset
df = pd.read_csv("Iris.csv")
  
ggplot(df) + aes(x="SepalLengthCm") + geom_histogram()
ggplot(df) + aes(x="Species", y="SepalLengthCm") + geom_boxplot()
```

```{python}
#from plotnine import geom_point
from plotnine import *
ggplot(df) + aes(x="Species", y="SepalLengthCm") + geom_point() + geom_smooth(method='lm')
ggplot(df) + aes(x="Species", y="SepalWidthCm") + geom_boxplot()
```



## numerical summary  
```{python}
pushupsData.groupby("position")['pushups'].describe().reset_index()	
```
fix the output to 2 decimals

## inferential results

```{python}
from scipy import stats
s = pushupsData['pushups'][(pushupsData["position"] == 'SKILL')]
l = pushupsData['pushups'][(pushupsData["position"] == 'LINE')]
 
t, p =stats.ttest_ind(s,l)
print(f"p-value is {p:.6f}")

```
## Conclusions


